# Generated by Django 4.1 on 2022-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
